upstream vaultwarden_app {
    server vaultwarden-app:8080;
}

server {
    listen 80;
    server_name _;

    server_tokens off;

    client_max_body_size 128M;

    # WebSocket notifications — sur le port principal depuis Vaultwarden v1.29
    location /notifications/hub {
        proxy_pass http://vaultwarden_app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 600s;
    }

    location / {
        proxy_pass http://vaultwarden_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 90s;
    }
}
